name: flutter_new_structure
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  http: ^1.2.2
  flutter_svg: ^2.0.14
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.2

  firebase_crashlytics: ^4.1.3
  firebase_core: ^3.6.0
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  injectable: ^2.5.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  get_it: ^8.0.1
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/png/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
