import 'dart:developer' as developer;

import 'package:dio/dio.dart';

/// An interceptor that generates cURL commands from HTTP requests
/// following Postman's formatting standards
class CurlInterceptor extends Interceptor {
  CurlInterceptor({this.enableLogging = true, this.printToConsole = true, this.onCurlGenerated});

  /// Enable/disable logging to console and log
  final bool enableLogging;

  /// Print to console (in addition to log). Set to false for log-only output.
  final bool printToConsole;

  /// Custom callback to handle the generated cURL command
  final Function(String curlCommand)? onCurlGenerated;

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    final curlCommand = _generateCurlCommand(options);

    if (enableLogging) {
      // Always log to developer log for easy copying from DevTools
      developer.log('\n$curlCommand', name: 'cURL', time: DateTime.now());

      // Optionally print to console
      if (printToConsole) {
        print('');
        print('🌐 cURL Command (${options.method} ${options.uri.path}):');
        print('─' * 80);
        print(curlCommand);
        print('─' * 80);
        print('');
      }
    }

    onCurlGenerated?.call(curlCommand);

    super.onRequest(options, handler);
  }

  String _generateCurlCommand(RequestOptions options) {
    final buffer = StringBuffer();

    // Start with curl command
    buffer.write('curl --location');

    // Add HTTP method if not GET
    if (options.method.toUpperCase() != 'GET') {
      buffer.write(' --request ${options.method.toUpperCase()}');
    }

    // Add URL with query parameters
    final uri = options.uri;
    buffer.write(" '$uri'");

    // Add Authorization header explicitly if present
    final authorizationHeader = options.headers.entries.firstWhere(
      (e) => e.key.toLowerCase() == 'authorization',
      orElse: () => const MapEntry<String, dynamic>('', null),
    );
    if (authorizationHeader.key.isNotEmpty && authorizationHeader.value != null) {
      buffer.write(
        " \\\n--header '${_escapeHeader(authorizationHeader.key)}: ${_escapeHeader(authorizationHeader.value.toString())}'",
      );
    }

    // Add headers except those skipped (including Authorization since it's added above if present)
    options.headers.forEach((key, value) {
      // Skip headers that Postman typically auto-generates or are handled separately
      // Also skip Authorization as it's already handled
      if (!_shouldSkipHeader(key) && key.toLowerCase() != 'authorization') {
        buffer.write(" \\\n--header '${_escapeHeader(key)}: ${_escapeHeader(value.toString())}'");
      }
    });

    // Add request body
    if (options.data != null) {
      buffer.write(_formatRequestBody(options));
    }

    return buffer.toString();
  }

  bool _shouldSkipHeader(String headerName) {
    final lowerKey = headerName.toLowerCase();
    // These headers are typically auto-generated by Postman or handled separately
    return lowerKey == 'content-length' || lowerKey == 'host' || lowerKey == 'connection';
  }

  String _formatRequestBody(RequestOptions options) {
    final buffer = StringBuffer();

    if (options.data is FormData) {
      // Handle multipart/form-data
      final formData = options.data as FormData;

      for (final field in formData.fields) {
        buffer.write(
          " \\\n--form '${_escapeFormField(field.key)}=\"${_escapeFormField(field.value)}\"'",
        );
      }

      for (final file in formData.files) {
        final multipartFile = file.value;

        // Use filename if available (set by fromFile, fromBytes, fromStream)
        // If no filename, use a descriptive fallback with the field key
        final fileReference = (multipartFile.filename != null && multipartFile.filename!.isNotEmpty)
            ? multipartFile.filename!
            : 'file_${file.key}';

        buffer.write(
          " \\\n--form '${_escapeFormField(file.key)}=@\"${_escapeFormField(fileReference)}\"'",
        );
      }
    } else if (options.data is Map) {
      // Handle JSON or form-urlencoded data
      final contentType = options.headers['content-type']?.toString().toLowerCase() ??
          options.headers['Content-Type']?.toString().toLowerCase() ??
          '';

      if (contentType.contains('application/x-www-form-urlencoded')) {
        // URL-encoded form data
        final data = options.data as Map;
        final encodedData = data.entries
            .map(
              (e) =>
                  '${Uri.encodeComponent(e.key.toString())}=${Uri.encodeComponent(e.value.toString())}',
            )
            .join('&');
        buffer.write(" \\\n--data-urlencode '${_escapeData(encodedData)}'");
      } else {
        // JSON data (default)
        final jsonString = _convertToJsonString(options.data);
        buffer.write(" \\\n--data-raw '${_escapeData(jsonString)}'");
      }
    } else if (options.data is String) {
      // Raw string data
      buffer.write(" \\\n--data-raw '${_escapeData(options.data as String)}'");
    } else {
      // Try to convert to JSON string
      final jsonString = _convertToJsonString(options.data);
      buffer.write(" \\\n--data-raw '${_escapeData(jsonString)}'");
    }

    return buffer.toString();
  }

  String _convertToJsonString(dynamic data) {
    try {
      // Try to encode as JSON
      if (data is Map || data is List) {
        return _jsonEncode(data);
      }
      return data.toString();
    } catch (e) {
      return data.toString();
    }
  }

  String _jsonEncode(dynamic data) {
    // Simple JSON encoding without external dependencies
    if (data == null) return 'null';
    if (data is String) return '"${_escapeJsonString(data)}"';
    if (data is num || data is bool) return data.toString();

    if (data is List) {
      final items = data.map(_jsonEncode).join(',');
      return '[$items]';
    }

    if (data is Map) {
      final entries = data.entries
          .map((e) => '"${_escapeJsonString(e.key.toString())}":${_jsonEncode(e.value)}')
          .join(',');
      return '{$entries}';
    }

    return '"${_escapeJsonString(data.toString())}"';
  }

  String _escapeJsonString(String str) {
    return str
        .replaceAll(r'\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r')
        .replaceAll('\t', r'\t');
  }

  String _escapeHeader(String value) {
    // Escape single quotes for shell safety
    return value.replaceAll("'", r"'\''");
  }

  String _escapeData(String data) {
    // Escape single quotes and handle special characters
    return data.replaceAll("'", r"'\''");
  }

  String _escapeFormField(String value) {
    // Escape double quotes and backslashes for form fields
    return value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
  }
}
